### ISSUE TITLE
Backlog - Implement backlog for tafel

### ISSUE THREAD

**Issue by prashanth-92** [prambrucke/tafel#2]
### Motivation: 
To have a list of items ready to be worked on.

### Tasks:

- [ ] Should be able to add / modify / delete / assign backlog items

- [ ] Should be able to prioritize items

- [ ] Provide suggestions when adding related backlogs

- [ ] Should be able to see the audit (activity)

- [ ] Should be able to attach related documents etc

- [ ] Should be able to label / tag items

- [ ] Enable text formatting / semantics like github. For eg: bold, italicize text

- [ ] User role/auth for back log
